[feature/kudago/categories] Получение списка всех доступных мест из сервиса KudaGo.
VerbitskiA/meetins-web-api pull request #18
Opened 2022-04-02 19:04 UTC by YanaLatysh03

2022-04-05 10:30 UTC, VerbitskiA requested changes

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Models/KudaGo/Results.cs
> +    public class Results
Изменить название класса

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Services/KudaGo/KudaGoRepository.cs
> +                var responseJson = await client.GetStringAsync(ApiUrl + ApiVersion + "/places/");
Не делать два запроса

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +    public class KudaGoPlacesOutput
Разобраться в получаемых данных

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        public string Next { get; set; }
Это ссылка на следующую страницу

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        /// </summary>
На предыдущую страницу

2022-04-05 10:30 UTC, VerbitskiA commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        public IEnumerable<Results> Results { get; set; }
Данные на странице с местами

2022-04-05 10:34 UTC, VerbitskiA commented
Подумать какие данные мы хотим запросить. Мы показываем список событий - подробная информация, такая как парковочные места, на не надо. Также нужно получать только актуальные события.

2022-04-09 16:06 UTC, YanaLatysh03 commented on Meetins.Models/KudaGo/Results.cs
> +    public class Results
Изменено название класса.

2022-04-09 16:06 UTC, YanaLatysh03 commented on Meetins.Services/KudaGo/KudaGoRepository.cs
> +                var responseJson = await client.GetStringAsync(ApiUrl + ApiVersion + "/places/");
Сделано.

2022-04-09 16:06 UTC, YanaLatysh03 commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +    public class KudaGoPlacesOutput
Сделано.

2022-04-09 16:07 UTC, YanaLatysh03 commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        public string Next { get; set; }
Удалено.

2022-04-09 16:07 UTC, YanaLatysh03 commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        /// </summary>
Удалено.

2022-04-09 16:07 UTC, YanaLatysh03 commented on Meetins.Models/KudaGo/KudaGoPlacesOutput.cs
> +        public IEnumerable<Results> Results { get; set; }
Сделано.

2022-04-14 10:04 UTC, VerbitskiA approved these changes

2022-04-14 10:05 UTC, merged