[feature/messenger] Создание контроллера, репозитория и сервиса для работы с диалогами и сообщениями.
VerbitskiA/meetins-web-api pull request #2
Opened 2022-02-18 18:10 UTC by YanaLatysh03

2022-02-21 06:37 UTC, VerbitskiA requested changes

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Abstractions/Repositories/IDialogsRepository.cs
> +        Task<IEnumerable<MessagesOutput>> GetMessagesOfDialog(Guid dialogId);
GetMessagesOfDialog**Async**

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Abstractions/Services/IDialogsService.cs
> +        Task<IEnumerable<MessagesOutput>> GetMessagesOfDialog(Guid dialogId);
GetMessagesOfDialog**Async**

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Contollers/DialogsController.cs
> +        /// <returns> Ok(result). </returns>
returns: диалоги пользователя.

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Contollers/DialogsController.cs
> +        /// <returns> Ok(messages). </returns>
returns: Сообщения пользователя.

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Models/Dialogs/DialogsOutput.cs
> +    }
Добавить комментарии. Переработать выходную модель диалогов: должны быть поля(на как Вконтакте например): Id диалога, с кем этот диалог(имя),с кем этот диалог(аватарка), последнее сообщение в диалоге, прочитано ли сообщение.

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Models/Dialogs/MessagesOutput.cs
> +    }
Добавить комменты и переработать. Должны быть поля(опять как в Вк как раскрываешь диалог): Id сообщения, контент, дата отправки, кто отправил(имя), кто отправил(аватарка), прочитано ли.

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Models/Entities/DialogMembersEntity.cs
>      public class DialogMembersEntity
Тут смотри задачу с таблицами, надо добавить внешние ключи.

2022-02-21 06:37 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +        }
Логика изменится, после добавления фиксов описанных выше.

2022-02-25 13:49 UTC, YanaLatysh03 commented on Meetins.Abstractions/Repositories/IDialogsRepository.cs
> +        Task<IEnumerable<MessagesOutput>> GetMessagesOfDialog(Guid dialogId);
Исправлено.

2022-02-27 09:55 UTC, VerbitskiA approved these changes

2022-02-27 09:55 UTC, merged