[Feature/profile] Полное удаление аккаунта пользователя, сообщений и диалогов.
VerbitskiA/meetins-web-api pull request #6
Opened 2022-03-11 21:02 UTC by YanaLatysh03

2022-03-13 06:57 UTC, VerbitskiA requested changes
Поправить названия, возвращаемые значения. Избавимся от сущности свойств сообщений, свойства будем хранить в таблице Messages.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Abstractions/Repositories/IDialogsRepository.cs
> +        Task<Task> DeleteAllUserDialogsAsync(Guid userId);
Добавить xml-комментарии.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Abstractions/Services/IDialogsService.cs
> +        Task<Task> DeleteAllUserDialogsAsync(Guid userId);
Комментарии.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Contollers/SettingsController.cs
> +        public async Task<IActionResult> DeleteAsync()
Возвращать bool значение, как статус проведенной операции. true - если получилось удалить всё. Надо будет изменить методы сервисов и репозиториев так же.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Core/Data/PostgreDbContext.cs
> +        public DbSet<MessagePropertiesEntity> ChatMessage { get; set; }
Изменить название свойства на MessagePropierties и поправить комментарий.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Models/Entities/MessageContentsEntity.cs
> +        [ForeignKey("MessageContents_MessageId_fkey")]
Поправить имя ключа.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Models/Entities/MessageEntity.cs
> +        public Guid UserId { get; set; }
Оставить название SenderId.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Models/Entities/MessagePropertiesEntity.cs
>  }
Давай вообще избавимся от этой сущности, а поле IsRead перенесем в таблицу Messages. Соответственно нужно поправить БД, контекст.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +        public async Task<Task> DeleteAllUserDialogsAsync(Guid userId)
Возвращать bool. true - если удаление прошло успешно. Если удаляются и сообщения назови метод соответсвенно.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                                SenderId = d.UserId,
Оставлять SenderId.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                    UserId = senderId,
Оставлять SenderId.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                                SenderId = d.UserId,
Оставлять SenderId.

2022-03-13 06:57 UTC, VerbitskiA commented on Meetins.Services/Dialogs/DialogsService.cs
> +        public async Task<Task> DeleteAllUserDialogsAsync(Guid userId)
return bool. Название метода.

2022-03-15 19:21 UTC, YanaLatysh03 commented on Meetins.Abstractions/Repositories/IDialogsRepository.cs
> +        Task<Task> DeleteAllUserDialogsAsync(Guid userId);
Исправлено

2022-03-15 19:22 UTC, YanaLatysh03 commented on Meetins.Abstractions/Services/IDialogsService.cs
> +        Task<Task> DeleteAllUserDialogsAsync(Guid userId);
Исправлено

2022-03-15 19:23 UTC, YanaLatysh03 commented on Meetins.Contollers/SettingsController.cs
> +        public async Task<IActionResult> DeleteAsync()
Исправлено

2022-03-15 19:23 UTC, YanaLatysh03 commented on Meetins.Models/Entities/MessagePropertiesEntity.cs
>  }
Исправлено

2022-03-15 19:23 UTC, YanaLatysh03 commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +        public async Task<Task> DeleteAllUserDialogsAsync(Guid userId)
Исправлено

2022-03-15 19:23 UTC, YanaLatysh03 commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                                SenderId = d.UserId,
Исправлено

2022-03-15 19:23 UTC, YanaLatysh03 commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                    UserId = senderId,
Исправлено

2022-03-15 19:24 UTC, YanaLatysh03 commented on Meetins.Services/Dialogs/DialogsRepository.cs
> +                                SenderId = d.UserId,
Сделано

2022-03-15 19:24 UTC, YanaLatysh03 commented on Meetins.Services/Dialogs/DialogsService.cs
> +        public async Task<Task> DeleteAllUserDialogsAsync(Guid userId)
Сделано

2022-03-16 08:23 UTC, VerbitskiA approved these changes

2022-03-16 08:23 UTC, VerbitskiA commented
[feature/profile] Полное удаление аккаунта пользователя, сообщений и диалогов. Дополнительные правки по другим вопросам.

2022-03-16 08:24 UTC, merged